---
- hosts: workers:controllers:servers
  #- hosts: all
  gather_facts: yes
  become: false
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }} {{ ansible_distribution_version}}"
