proxy:
  secretToken: "a86812ddeccccf87c14148f4ab629f7991da41e77d4a6bf470943f0131c24917"
singleuser:
  image:
    # Get the latest image tag at:
    # https://hub.docker.com/r/jupyter/datascience-notebook/tags/
    # Inspect the Dockerfile at:
    # https://github.com/jupyter/docker-stacks/tree/master/datascience-notebook/Dockerfile
    name: jupyter/scipy-notebook
    tag: ad3574d3c5c7
    #    tag: 2ce7c06a61a1
  defaultUrl: "/lab"
  storage:
    capacity: "2Gi"
  extraEnv:
    EDITOR: "vim"
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
