---
apiVersion: v1
kind: Pod
metadata:
    name: gs-test-pod
    labels:
        name: gs-test-pod
        context: dev-k8s-lab
spec:
    containers:
    - image: openweb/git-sync
      name: git-sync
      imagePullPolicy: Always
      env:
      - name: GIT_SYNC_REPO
        value: https://github.com/trevor-crowley/mysite2.git
      volumeMounts:
      - mountPath: "/git"
        name: www
    volumes:
    - name: www
      emptyDir: {}
