---
apiVersion: v1
kind: Pod
metadata:
    name: mysite
    labels:
        name: mysite
        context: dev-k8s-lab
spec:
    containers:
    - image: nginx
      name: website
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: www
        readOnly: true
    - image: googlecontainer/git-sync
      name: git-sync
      imagePullPolicy: Always
      env:
      - name: GIT_SYNC_REPO
        value: git@github.com:trevor-crowley/mysite.git
      - name: GIT_SYNC_SSH
        value: 'true'
      - name: GIT_SYNC_WAIT
        value: '10'
      volumeMounts:
      - mountPath: "/git"
        name: www
      - mountPath: "/etc/git-secret"
        name: git-secret
    volumes:
    - name: www
      emptyDir: {}
    - name: git-secret
      secret:
        secretName: git-creds
        defaultMode: 256

          

