---
apiVersion: v1
kind: Pod
metadata:
    name: ng-test-pod
    labels:
        name: ng-test-pod
        context: dev-k8s-lab
spec:
    containers:
    - image: nginx
      name: website
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: www
    volumes:
    - name: www
      emptyDir: {}
