apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0021 
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: default
    name: data-my-redmine-mariadb-0
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs/home/k8s/redmine-db
    server: 192.168.88.138
