apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0030 
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: default
    name: prometheus-server
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs/home/k8s/prometheus-server 
    server: 192.168.88.138
