---
apiVersion: v1
kind: Pod
metadata:
    name: mysite-pod
    labels:
        name: mysite-pod
        context: dev-k8s-lab
spec:
    containers:
    - image: nginx
      name: website
      ports:
      - containerPort: 80
      volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: www
        readOnly: true
    - image: openweb/git-sync
      name: git-sync
      imagePullPolicy: Always
      env:
      - name: GIT_SYNC_REPO
        value: https://github.com/trevor-crowley/mysite2.git
      - name: GIT_SYNC_DEST
        value: /git
      - name: GIT_SYNC_BRANCH
        value: master  
      - name: GIT_SYNC_REV
        value: FETCH_HEAD
      - name: GIT_SYNC_WAIT
        value: '10'
      volumeMounts:
      - mountPath: "/git"
        name: www
    volumes:
    - name: www
      emptyDir: {}
