apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0050 
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: default
    name: grafana
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs/home/k8s/grafana
    server: 192.168.88.138
