apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002 
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  claimRef:
    namespace: jhub
    name: claim-trevor
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/nfs/home/k8s/hub-db-trevor
    server: 192.168.88.138
