apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.2.116    
  selector:
    app: blog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 2368
